engines:
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Lint/UnderscorePrefixedVariableName:
        enabled: false
      Rubocop/Metrics/LineLength:
        enabled: true 
        max: 85
ratings:
  paths:
  - Gemfile.lock
  - "**.css"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
  - "**.rb"
exclude_paths:
- config/**/*
- db/**/*
- spec/**/*
- vendor/**/*
- app/assets/images/swagger/**/*
- app/assets/javascripts/swagger/**/*
- app/assets/stylesheets/swagger/**/*
