dbdata:
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL'
  volumes:
    - /var/lib/postgresql/data

db:
  image: postgres
  volumes_from:
    - dbdata

web:
  build: .
  command: bundle exec rails s -p 3000 -b 0.0.0.0
  volumes:
    - .:/backend
  ports:
    - "3000:3000"
  links:
    - db