dbdata:
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL'
  volumes:
    - /var/lib/postgresql/data

db:
  image: postgres
  volumes_from:
    - dbdata

web:
  build: .
  volumes:
    - .:/backend
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    - DATABASE_HOST=db
    - RAILS_ENV=development